### ISSUE TITLE
How to insert image into README

### ISSUE THREAD

**Issue by jdebacker** [compute-tooling/compute-studio#201]
I'm trying to insert an image into the README on the publish details.  I can embed an image via markdown, but I can't change it's size.  I also cannot insert html into the README that would give me more flexibility in sizing and positioning the image.

Are there any suggestions?  I thought one could generally use html syntax within a markdown doc.

Any help is appreciated. Thanks!

**Comment by hdoupe** [comment]
Hmm, you should be able to set the height and width attributes on the `img` tag. For example, the C/S logo is coded like this:

```html
<img src="/static/imgs/cslashs.fbad3dcaaa33.png" width="30" height="30" alt="Compute Studio">
```

**Comment by jdebacker** [comment]
@hdoupe Thank for following up so quickly. It did work!  It just doesn't work in the "preview" so I didn't think the html was taking effect - but it works perfectly when published.

**Comment by hdoupe** [comment]
No problem! It looks like there are some discrepancies between the markdown renderer for the details page and the one used on the inputs page.

I found that these dimensions with some centering look nice:
```html
<p class="d-flex justify-content-center">
  <img src="https://www.ospc.org/images/ccc.png" alt="CCC Logo" width="500" height="200">
</p>
```
