### ISSUE TITLE
Testing apps locally

### ISSUE THREAD

**Issue by jdebacker** [compute-tooling/compute-studio#219]
@hdoupe Are there any instructions for testing an app locally?  E.g., I'm seeing some formatting issues that I'd like to adjust with the results page for CCC, but don't want to burden you with installing new versions of my packages.  If I could follow instructions to run these locally, I could fine tune the formatting before you need to put a new model version on CS.

cc @rickecon

**Comment by hdoupe** [comment]
This is something I've been thinking about lately. There are two levels of doing this:

1. be able to view your inputs and outputs given a JSON file from `get_inputs` and a JSON file from `run_model`
    - This seems like the solution that would be most helpful for CS publishers: you get an idea of how things will look before pushing to compute.studio and you don't have to tangle with docker, kubernetes, and cloud compute/storage services.
    - This could also be hosted on [compute.studio](https://compute.studio). All the publishers would have to do is upload the two JSON files.


2. fully deploy compute studio, kubernetes cluster and all
    - This seems like the ideal solution for developers who plan to make changes to the CS codebase and/or infrastructure. JupyterHub's [zero to k8s project](https://github.com/jupyterhub/zero-to-jupyterhub-k8s) is a good model for how this should work.

There may be other solutions that fall in between 1 and 2. I think I could get a solution with 1 up in the next couple weeks, but 2 is a longer term project.

In the mean time, @jdebacker I'm happy to push as often as you'd like. Just ask @peter-metz, I usually get the updates up within a couple hours. You can "trigger a build" by pinging me in an issue, emailing me, or dropping a message in [riot](https://riot.im/app/#/room/#compute-studio:matrix.org). Is this an ok work flow until solution (1) is completed?

**Comment by jdebacker** [comment]
@hdoupe Yes - pining you works for me indefinitely.  I just want to raise this issue as I want to save you work if the model maintainers can do some of this testing on their own.

Thanks for thinking about the options here.

**Comment by hdoupe** [comment]
Ha, cool. No problem. Closing the issue. I opened a couple other issues (#220, #221) to reference the options 1 and 2.
