### ISSUE TITLE
Guide question

### ISSUE THREAD

**Issue by MaxGhenis** [compute-tooling/compute-studio#225]
https://docs.compute.studio/publish/functions has this snippet:
```
import matchups

def get_inputs(meta_params_dict):
    meta_params = MetaParams()
    meta_params.adjust(meta_params_dict)
    params = MatchupsParams()
```
Should the `MetaParams()` and `MatchupsParams()` have a `matchups.` prefix?

**Comment by hdoupe** [comment]
Yep, you're right. Just updated the docs site. Thanks for the bug report.

**Comment by hdoupe** [comment]
Closing #225. Thanks for the bug report @MaxGhenis. Feel free to open other issues if you have any more questions.
