### ISSUE TITLE
PNG files on Compute Studio Pages

### ISSUE THREAD

**Issue by jdebacker** [compute-tooling/compute-studio#228]
Right now, Compute Studio reads in a PNG file from memory to display on the web. 

Is CS ok in caching all these PNG files separately from the HTML files for the results pages?

If not, one solution would be to [encode the PNG and add that to the directly to the HTML](https://stackoverflow.com/questions/48717794/matplotlib-embed-figures-in-auto-generated-html
).

**Comment by hdoupe** [comment]
> Is CS ok in caching all these PNG files separately from the HTML files for the results pages?

I'm not quite sure what you're asking. Can you elaborate?

Btw, I'm planning to use the approach similar to the one in your link. I plan to have a PR open with those changes in the next day or two. I've tested this approach out locally, and it's worked well.

**Comment by jdebacker** [comment]
@hdoupe What I intended to ask was if Compute Studio was ok in hosting both the html file with the results page + the png files with the image to embed in that results page (2 files) as opposed to just one html file (with, e.g., the html code for a table or figure as part of that single file)?  

> Btw, I'm planning to use the approach similar to the one in your link. I plan to have a PR open with those changes in the next day or two. I've tested this approach out locally, and it's worked well.

Sounds great - was thinking this would require changes on my end, in `functions.py`

**Comment by hdoupe** [comment]
Ah, I see. Yep, OG-USA is good to go.

If you're curious, all of the outputs are stored as files in a storage bucket, and the C/S webapp just keeps the corresponding file names. When someone views the outputs of a sim, the data is downloaded to the webserver, loaded into the html page, and sent off to the user.

**Comment by hdoupe** [comment]
Closing #228
