### ISSUE TITLE
Rendering math symbols in HTML output

### ISSUE THREAD

**Issue by jdebacker** [compute-tooling/compute-studio#264]
Can C/S add the capability to render math equations using MathJax or similar?  E.g., for output like this table from OG-USA:

<img width="552" alt="Screen Shot 2020-02-02 at 4 12 26 PM" src="https://user-images.githubusercontent.com/10715924/73615572-fb521580-45d6-11ea-8639-dfa068400e9e.png">

**Comment by hdoupe** [comment]
Thanks for opening the issue @jdebacker. I think adding MathJax support would be sweet. I'll take a look at it this week.

**Comment by hdoupe** [comment]
Pinging myself on this
