### ISSUE TITLE
Some spaces between words are missing in OG-USA README

### ISSUE THREAD

**Issue by MaxGhenis** [compute-tooling/compute-studio#285]
From https://compute.studio/PSLmodels/OG-USA:

![image](https://user-images.githubusercontent.com/6076111/81983221-dd3d7d80-95e7-11ea-85a4-a062d3ba56c0.png)

Looks to be identical to https://github.com/PSLmodels/OG-USA#disclaimer but with some spaces between words missing, and also headings not rendering properly.

Filing here as I didn't see e.g. `guaranteeof` anywhere in the OG-USA repo (though I don't see it here either).

**Comment by hdoupe** [comment]
@jdebacker @rickecon This looks like a typo. Let me know if it's not and I'll investigate.

**Comment by hdoupe** [comment]
Thanks for the bug report @MaxGhenis !
