### ISSUE TITLE
Consistent title/chart alignment between preview and full-screen

### ISSUE THREAD

**Issue by MaxGhenis** [compute-tooling/compute-studio#312]
Chart titles are centered with respect to the chart in previews:
![image](https://user-images.githubusercontent.com/6076111/89327771-4362fb00-d641-11ea-8d22-10582d4c399a.png)

but left-aligned when viewing charts full-screen:
![image](https://user-images.githubusercontent.com/6076111/89327805-507fea00-d641-11ea-881f-8fe1bc3bbdd8.png)

Example from https://compute.studio/PSLmodels/OG-USA/142/

**Comment by hdoupe** [comment]
Nice catch @MaxGhenis. I'll get a fix up tomorrow.

**Comment by hdoupe** [comment]
@MaxGhenis Titles are centered now. Thanks for pointing this out!
