### ISSUE TITLE
Create a Python wrapper for the existing Actions workflow

### ISSUE THREAD

**Issue by hdoupe** [compute-tooling/compute-studio#437]
Automate the process of:
- pushing a config change to [compute-studio-publish](https://github.com/compute-tooling/compute-studio-publish)
- opening a PR with the updated file
- monitor gh action run status
- merge if tests pass
- monitor deployment status

**Comment by MattHJensen** [comment]
@hdoupe, can this be closed?

**Comment by hdoupe** [comment]
Yep, thanks @MattHJensen
