### ISSUE TITLE
Review of Tax-Brain app

### ISSUE THREAD

**Issue by MattHJensen** [compute-tooling/compute-studio#88]
- [x] benefit params and others are showing up as blank. I believe the problem is that booleans are not displaying. 
- [x] default param values should be displayed beneath after a values has been edited. These should also be displayed when the page is returned to later via url. 
- [x] the * and < operators are not working. (I'm not sure if this is a Tax-Brain or COMP issue.)
- [x] the cpi buttons should be light gray when they are unselected. (or something else should be done to make it clear when they are unselected and selected.) 
- [x] the Tax-Brain version should be displayed on the input and output page.
- [x] the build table widgets should be centered like the edit inputs and download results buttons. 
- [x] font sizes across the entire site seem quite small. I preferred ospc.org/taxbrain sizes. 
- [x] column widths are too narrow, especially on the output page. Seems like tables are not currently responsive to window size, as on ospc.org/taxbrain. That would be nice.
- [x] for @andersonfrailey: user tips should be added to the model overview. 
- [x] hdoupe/tax-brain no longer needed from models drop down. 
- [x] Clicking "hi [username]" in upper takes me to an under construction page. Should take me home. 
- [x] the content expanders +/- buttons only show + now, even when expanded. 
- [x] `Behavior` section header is showing up twice. 
- [x] The left parameter (policy/behavior) nav column should slide up and down w scrolling, and ideally highlight the section where the user is. 
- [x] desensitize case in COMP URLs. e.g.,  https://www.compmodels.com/PSLmodels/tax-brain/ 404s.

**Comment by hdoupe** [comment]
Thanks for the review @MattHJensen. I'll try to knock out a chunk of these today.

**Comment by hdoupe** [comment]
>  the Tax-Brain version should be displayed on the input and output page.

The version should be specified in the results attribute as describe [here][1]. I don't think it is set right now.

cc @andersonfrailey

[1]: https://github.com/comp-org/comp/blob/master/docs/IOSCHEMA.md#outputs

**Comment by andersonfrailey** [comment]
>  for @andersonfrailey: user tips should be added to the model overview.

What kind of user tips do you have in mind? Just the ones that are in the overview of Tax-Brain 1.0.0?

**Comment by MattHJensen** [comment]
I only have the tax-brain 1.0.0 tips in mind.

What kind of user tips do you have in mind? Just the ones that are in the overview of Tax-Brain 1.0.0?

**Comment by andersonfrailey** [comment]
Had to edit them a bit to stay under the character limit, but they're added now.

**Comment by hdoupe** [comment]
I'm open to bumping up the character limit or getting rid of it. What do you think @andersonfrailey ?

**Comment by andersonfrailey** [comment]
@hdoupe, a bump to 1,500 would probably be sufficient for most projects.

**Comment by MattHJensen** [comment]
> @hdoupe, a bump to 1,500 would probably be sufficient for most projects.

Maybe:
- [ ] drop the character count
- [ ] call it a readme instead of an overview. 
- [ ] Ideally would support markdown, but I guess this is a longer term thing. 
- [ ] Add a one-liner.

**Comment by hdoupe** [comment]
These make sense to me. Markdown is already supported to some extent. It looks like adding headers and bullets broke the publish page. However, it renders just fine on the model home page:

![Screen Shot 2019-03-26 at 1 21 31 PM](https://user-images.githubusercontent.com/9206065/55018872-1d980180-4fca-11e9-98c5-222d73ce7d8a.png)

**Comment by hdoupe** [comment]
- [ ] Dropdown for boolean variables and variables using the choice validator

**Comment by hdoupe** [comment]
Finally closing out #88 by allowing case-insensitive urls (#233). Thanks for the extensive checklist @MattHJensen!

**Comment by MattHJensen** [comment]
Thanks, @hdoupe!
